In [5]:
# Задание 1. Импортируйте библиотеку Numpy и дайте ей псевдоним np.
# Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 
# Найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
import numpy as np
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11], 
              [3, 10], 
              [1, 7]])
print(a)
mean_a=a.mean(axis = 0)
mean_a

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


array([2. , 8.4])

In [6]:
# Задание 2. Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков,
#содержащиеся в массиве mean_a. 
a_centered=np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [13]:
# Задание 3. Найдите скалярное произведение столбцов массива a_centered. 
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.
s1=a_centered[:,0]
s2=a_centered[:,1]
a_centered_sp=np.dot(a1,a2)
print(a_centered_sp)
N=a.shape[0]
print(N)
covar=a_centered_sp/(N-1)
covar


8.0
5


2.0

In [14]:
# Задание 4. Вычислить ковариацию с помощью функции np.cov. 
# В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. 
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])